---
- name: Add custom sources.list
  copy: 
    src: sources.list
    dest: /etc/apt/
    owner: root
    group: root
    mode: '0644'

- name: Copying over update skript
  copy:
    src: update
    dest: /etc/cron.daily/update
    owner: root
    group: root
    mode: '0755'

- name: Updating package cache
  apt:
    update_cache: yes