---
- name: Add custom sources.list
  copy: 
    src: files/apt/sources.list
    dest: /etc/apt/
    owner: root
    group: root
    mode: '0644'
  notify: update apt cache

- name: Make sure the APT cache is updated
  meta: flush_handlers

- name: Copying over update skript
  copy:
    src: files/apt/update
    dest: /etc/cron.daily/update
    owner: root
    group: root
    mode: '0755'
