---
- name: Installing Fail2Ban
  apt:
    name: fail2ban
    state: present

- name: Copying config file (Fail2Ban)
  template: 
    src: jail.local.j2 
    dest: /etc/fail2ban/jail.local
    mode: 0640
  notify: restart fail2ban