---
- name: Add custom NTP config
  template: 
    src: timesyncd.conf.j2 
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
  notify: restart timesyncd

- name: Enable NTP sync
  shell: timedatectl set-ntp true
