---
- name: Installing UFW
  apt:
    name: ufw
    state: present

- name: Enable SSH access
  ufw:
    rule: allow
    name: OpenSSH

- name: Enabling UFW
  ufw:
    state: enabled
    policy: deny