---
- name: Updating package cache (1/4)
  apt:
    update_cache: yes

- name: Updating system (2/4)
  apt:
    name: "*"
    state: latest

- name: Autoremove packages (3/4)
  apt:
    autoremove: yes

- name: Autoclean packages (4/4)
  apt:
    autoclean: yes

