- name: (debsecan) Setup debconf (1/3)
  debconf:
    name: debsecan
    question: debsecan/report
    value: 'false'
    vtype: select

- name: (debsecan) Setup debconf (2/3)
  debconf:
    name: debsecan
    question: debsecan/suite
    value: 'bullseye'
    vtype: select

- name: Installing debsecan
  apt:
    name: debsecan
    state: present